src/Mens2020.Mvc/Controllers/HomeController.cs
using Mens2020.DataSource.DataSource;
using Mens2020.DataSource.Models;
using Microsoft.AspNet.Identity;
using System.Data.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using Mens2020.Mvc.Models;

namespace Mens2020.Mvc.Controllers
{
    public class HomeController : Controller
    {
        private Capstone2020Context db = new Capstone2020Context(nameof(Capstone2020Context));

        [Authorize]
        public ActionResult Index()
        {
            using (var db = new Capstone2020Context(nameof(Capstone2020Context)))
            {

                var currentUser = User.Identity.GetUserId();

                var todayAsDayEnum = (int)DateTime.Today.DayOfWeek.ConvertToDay();

                var currentUserAllGoalList = from loggedInUserEvent in db.UserEvents.Include(u => u.User)
                                        where currentUser == loggedInUserEvent.UserId                                     
                                        select loggedInUserEvent
                              ;

                var currentUserEvents = from loggedInUserEvent in db.UserEvents.Include(u => u.User)
                                        where currentUser == loggedInUserEvent.UserId
                                        where (loggedInUserEvent.RecurID & todayAsDayEnum) == todayAsDayEnum
                                        select loggedInUserEvent
                                ;




                if (currentUserAllGoalList.Count() > 0)
                {


                    return View("ExpUser", currentUserEvents.ToList());
                }
                else
                {
                    return View("NewUser");
                }


            }

        }
        public ActionResult About()

        {

            return View();


        }
        public ActionResult Contact()

        {

            return View();


        }

        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserEvent userEvent = db.UserEvents.Find(id);
            if (userEvent == null)
            {
                return HttpNotFound();
            }
            return View(userEvent);
        }

        // GET: UserEvents/Create
        public ActionResult CreateQuick()
        {
            using (var db = new Capstone2020Context(nameof(Capstone2020Context)))
            {
                ViewBag.UserId = new SelectList(User.Identity.GetUserName(), "Id", "FirstName");
            }
            return View();
        }

        // POST: UserEvents/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateQuick([Bind(Include = "UserEventId,EventTypeId,ParentId,CreationDate,CompletedDate,EventTitle," +
            "EventText,ColorID,ModificationDatetime,RevisionID,RecurID,UserId,RecurIntValue,SundayClickedBool," +
            "MondayClickedBool,TuesdayClickedBool,WednesdayClickedBool,ThursdayClickedBool,FridayClickedBool,SaturdayClickedBool")] UserEventModels userEvents)
        {
            using (var db = new Capstone2020Context(nameof(Capstone2020Context)))
            {
                if (userEvents.SundayClickedBool)
                {
                    userEvents.RecurIntValue += (int)Day.Sunday;
                }
                if (userEvents.MondayClickedBool)
                {
                    userEvents.RecurIntValue += (int)Day.Monday;
                }
                if (userEvents.TuesdayClickedBool)
                {
                    userEvents.RecurIntValue += (int)Day.Tuesday;
                }
                if (userEvents.WednesdayClickedBool)
                {
                    userEvents.RecurIntValue += (int)Day.Wednesday;
                }
                if (userEvents.ThursdayClickedBool)
                {
                    userEvents.RecurIntValue += (int)Day.Thursday;
                }
                if (userEvents.FridayClickedBool)
                {
                    userEvents.RecurIntValue += (int)Day.Friday;
                }
                if (userEvents.SaturdayClickedBool)
                {
                    userEvents.RecurIntValue += (int)Day.Saturday;
                }

                userEvents.UserEventId = Guid.NewGuid().ToString();

                userEvents.RevisionID = 0;

                userEvents.UserId = User.Identity.GetUserId();

                DateTime CreationDateTimeValue = DateTime.Now;


                var @event = new UserEvent
                {
                    UserEventId = userEvents.UserEventId,
                    UserId = userEvents.UserId,
                    ColorID = 1,
                    CompletedDate = userEvents.CompletedDate,
                    CreationDate = CreationDateTimeValue,
                    EventTitle = userEvents.EventTitle,
                    EventText = userEvents.EventText,
                    RecurID = userEvents.RecurIntValue,
                    EventTypeId = 1


                };
                db.UserEvents.Add(@event);


                db.SaveChanges();
                return RedirectToAction("Index");

            }
        }

        // GET: UserEvents/Edit/5
        public ActionResult Edit(string id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserEvent userEvent = db.UserEvents.Find(id);
            if (userEvent == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserId = new SelectList("Id", userEvent.UserId);
            return View(userEvent);

        }

        // POST: UserEvents/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserEventId,EventTypeId,ParentId,CreationDate,CompletedDate,EventTitle,EventText,ColorID,ModificationDatetime,RevisionID,RecurID,UserId")] UserEvent userEvent)
        {
            using (var db = new Capstone2020Context(nameof(Capstone2020Context)))
            {
                if (ModelState.IsValid)
                {
                    var dbValue = db.UserEvents.Find(userEvent.UserEventId);

                    dbValue.RevisionID += 1;
                    dbValue.ModificationDatetime = DateTime.Now;
                    dbValue.EventTitle = userEvent.EventTitle;
                    dbValue.EventText = userEvent.EventText;

                    // userEvent.UserId = dbValue.UserId;
                    userEvent.UserEventId = dbValue.UserEventId;
                    userEvent.EventTypeId = dbValue.EventTypeId;
                    userEvent.CreationDate = dbValue.CreationDate;
                    userEvent.EventTitle = dbValue.EventTitle;
                    userEvent.EventText = dbValue.EventText;
                    userEvent.RecurID = dbValue.RecurID;
                    userEvent.RevisionID = dbValue.RevisionID;


                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                ViewBag.UserId = new SelectList("Id", userEvent.UserId);
                return View(userEvent);
            }
        }

        // GET: UserEvents/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserEvent userEvent = db.UserEvents.Find(id);
            if (userEvent == null)
            {
                return HttpNotFound();
            }
            return View(userEvent);
        }

        // POST: UserEvents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            UserEvent userEvent = db.UserEvents.Find(id);
            db.UserEvents.Remove(userEvent);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/Mens2020.Mvc/Controllers/_GoalController.cs
using System;
using System.Globalization;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using Mens2020.Mvc.Models;
using Mens2020.DataSource.Models;
using Mens2020.DataSource.DataSource;
using System.Collections.ObjectModel;
using System.Runtime.Remoting.Contexts;
using System.Data.Entity;

namespace Mens2020.Mvc.Controllers
{
    [Authorize]
    public class _GoalController : Controller
    {
        // GET: _Goal
        public ActionResult Index()
        {
            return View();
        }

        // GET: _Goal/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: _Goal/Create
        public ActionResult Create()


        {

            return View();


        }

        // POST: _Goal/Create
        [HttpPost]
        // public ActionResult Create([Bind(Include = "LastName, FirstMidName, EnrollmentDate")] Student student)

        public ActionResult Create(CreateGoalModel model)
        {
     
            using (var db = new Capstone2020Context(nameof(Capstone2020Context)))
            {


                model.UserEventId = Guid.NewGuid().ToString();
                model.RevisionID = 0;
                var @event = new UserEvent
                {
                    UserEventId = model.UserEventId,
                    UserId = User.Identity.GetUserId(),
                    ColorID = 1,
                    CompletedDate = model.CompletedDate,
                    CreationDate = DateTime.Now,
                    EventTitle = model.EventTitle,
                    EventText = model.EventText,
                    RecurID = 0,
                    EventTypeId = 1

                };
                string CurrentUserId = User.Identity.GetUserId();
                db.Set<UserEvent>().Add(@event);

                db.SaveChanges();


            }


            return RedirectToAction("Index");



        }
        // GET: _Goal/Edit/5
        public ActionResult Edit(int id)
        {

            return View();

        }

        // POST: _Goal/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, CreateGoalModel model)
        {
            if (ModelState.IsValid)
            {
                // TODO: Add update logic here
                using (var db = new Capstone2020Context(nameof(Capstone2020Context)))
                {
                    model.RevisionID = model.RevisionID + 1;




                    db.SaveChanges();

                }



                return RedirectToAction("Index");
            }

            else
            {
                return View(model);
            }
        }

        // GET: _Goal/Delete/5
        public ActionResult Delete(int id)
        {


            return View();
        }

        // POST: _Goal/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try

            {

                using (var db = new Capstone2020Context(nameof(Capstone2020Context)))
                {
                    // db.UserEvents.Remove(UserEvent id);


                }
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        [Authorize]
        public ActionResult CreateGuided()
        {
            return View();
        }
        [Authorize]
        public ActionResult CreateQuick()
        {
            return View();
        }
        [Authorize]
        public ActionResult ChooseCreateType()
        {
            return View();
        }
        [Authorize]
        public ActionResult AllGoals()
        {
            
                using (var db = new Capstone2020Context(nameof(Capstone2020Context)))
                {
                    var currentUser = User.Identity.GetUserId();

                    var currentUserAllGoalList = from loggedInUserEvent in db.UserEvents.Include(u => u.User)
                                                 where currentUser == loggedInUserEvent.UserId
                                                 select loggedInUserEvent
                                     ;

                    return View(currentUserAllGoalList.ToList());
                }
            
        }
    }
}

src/Mens2020.Mvc/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
@section scripts{
    <style>
        tab1 {padding-left:4em}
        tab2 {padding-left:16em}
    </style>
}
<h2 style="text-align:center">@ViewBag.Title.</h2>
<h3 style="text-align:center">ReadySetGoal!</h3>
<p style="margin-top:35px">
    <tab1>
        Setting goals is difficult. Remembering and keeping to them makes it harder. Working with a mentor is very helpful, but only when the mentor is with you. <br /> <br />
        <tab1>We are developing a solution that can be really helpful. We aim to build an easy-to-use App. Set your goal, then record your goal in a place you can access easily.
        The best part, you can do this with your mentor, even when he’s not with you. This app will allow you an easy and simple ability to be in contact with your mentor.
        You can send messages, talk face-to-face or even share drawn ideas. Giving encouragement and recording how much you have accomplished will make it much easier to reach your goal!<br /> <br />
        <tab1>To reach a goal, it is easier to have a relaxed mentality. If you find a similar type of helpmate that is expensive, complicated and stressful to use, it may be easier to reach your goal without it.
        We aim for simplicity, to be easy to use, and share a mutual goal: <br /> <br />
            <p style="text-align:center"><b>OUR GOAL IS TO HELP YOU ACHIEVE YOUR GOAL!</b></p> 
</p>

src/Mens2020.Mvc/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
@section scripts{
    <style>
        td{
            padding-left:5em
        }
    </style>
}
    <h2>@ViewBag.Title.</h2>
    <h3>Keep in Touch (even during corona)</h3>


    <table>
        <tr>
            <td>Crossman, Daniel</td>
            <td>0587632265</td>
            <td>dan.crossman@yahoo.com</td>
        </tr>
        <tr>
            <td>Dan Soucie, David</td>
            <td>0549150244</td>
            <td>newninja.david@gmail.com</td>
        </tr>
        <tr>
            <td>Greenstien, Yitzy</td>
            <td>0527655707</td>
            <td>yitzy.greenstein1@gmail.com</td>
        </tr>
        <tr>
            <td>Ost, Naftoli</td>
            <td>0586238654</td>
            <td>naftoliyost@gmail.com</td>
        </tr>
        <tr>
            <td>Simon, Nosson Dovid</td>
            <td>0587095658</td>
            <td>nossondsimon@gmail.com</td>
        </tr>
        <tr>
            <td>Staum, Yaakov</td>
            <td>0583232056</td>
            <td>yakstaum@gmail.com</td>
        </tr>
    </table>

src/Mens2020.Mvc/Views/Home/CreateQuick.cshtml
@model Mens2020.Mvc.Models.UserEventModels
@{
    ViewBag.Title = "CreateQuick";
}

@section scripts{
    <link rel="stylesheet" type="text/css" href="~/Content/AppStyle.css">
    <link rel="stylesheet" type="text/css" href="~/Content/GoalCreaterStyle.css">

    <style>
        .red {
            background-color: red;
        }

        .orange {
            background-color: orange;
        }

        .yellow {
            background-color: yellow;
        }

        .green {
            background-color: green;
        }

        .darkblue {
            background-color: dodgerblue;
        }

        .purple {
            background-color: mediumpurple;
        }

        .pink {
            background-color: lightpink;
        }

        .brown {
            background-color: sandybrown;
        }

        .tan {
            background-color: tan;
        }

        .grey {
            background-color: gainsboro;
        }
    </style>
    <script>
        


        window.addEventListener("load", function () {
            document.querySelector("#goalInput").addEventListener("submit", function (e) {
                var txt = document.querySelector("[name=Goal]").value;
                document.querySelector("#Goal").innerHTML = txt;
                document.querySelector("#ShowGoal").style.display = "block";
                document.querySelector("#finishGoal").style.display = "block";
                document.querySelector("#goalInput").style.display = "none";

                e.preventDefault();
            });
        });

        window.onload = function () {
            document.querySelector("#color").addEventListener("click", function (e) {
                document.querySelector("#pop-up").style.display = "block";
                document.querySelector("#color-chooser").style.display = "block";
            });
            document.querySelector("#recursion").addEventListener("click", function (e) {
                document.querySelector("#pop-up").style.display = "block";
                document.querySelector("#recursion-form").style.display = "block";
            });
            document.querySelector("#close-color").addEventListener("click", function (e) {
                document.querySelector("#pop-up").style.display = "none";
                document.querySelector("#color-chooser").style.display = "none";
            });
            document.querySelector("#close-recursion").addEventListener("click", function (e) {
                document.querySelector("#pop-up").style.display = "none";
                document.querySelector("#recursion-form").style.display = "none";
            });
        };

        function selectBackground() {
            var e = document.getElementById("selector");
            var BackgroundValue = e.options[e.selectedIndex].value;
            document.getElementById("selector").style.backgroundColor = BackgroundValue;
        }

    </script>
}

<h2>CreateQuick</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <div>
        <div class="form-group">
            @Html.LabelFor(model => model.EventTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventText, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventText, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventText, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.ColorId, htmlAttributes: new { @class = "control-label col-md-2" })

            <select id=selector>
                <option value="white" class="transparent">Select Color</option>
                <option class="red" value="red">red</option>
                <option class="orange" value="orange">orange</option>
                <option class="yellow" value="yellow">yellow</option>
                <option class="green" value="green">green</option>
                <option class="darkblue" value="darkblue">blue</option>
                <option class="purple" value="purple">purple</option>
                <option class="pink" value="pink">pink</option>
                <option class="brown" value="brown">brown</option>
                <option class="tan" value="tan">tan</option>
                <option class="grey" value="grey">grey</option>
            </select>
            <button type="button" onclick="selectBackground()">Preview</button>
        </div>
    </div>

    <div  class ="form-group" >
        @Html.HiddenFor(model => model.RecurIntValue)
        <div>
            @Html.CheckBoxFor(model => model.SundayClickedBool )
            Sunday
            <br />
            @Html.CheckBoxFor(model => model.MondayClickedBool)
            Monday
            <br />
            @Html.CheckBoxFor(model => model.TuesdayClickedBool)
            Tuesday
            <br />
            @Html.CheckBoxFor(model => model.WednesdayClickedBool)
            Wednesday
            <br />
            @Html.CheckBoxFor(model => model.ThursdayClickedBool)
            Thursday
            <br />
            @Html.CheckBoxFor(model => model.FridayClickedBool)
            Friday
            <br />
            @Html.CheckBoxFor(model => model.SaturdayClickedBool)
            Saturday
            <br />
            @Html.CheckBoxFor(model => model.EverydayClickedBool)
            Daily
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>

    <div>
        @Html.ActionLink("Back to List", "Index", "Home")
    </div>
}

src/Mens2020.Mvc/Views/Home/Delete.cshtml
@model Mens2020.DataSource.Models.UserEvent

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserEvent</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.User.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventTypeId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventTypeId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ParentId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ParentId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompletedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompletedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventText)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ColorID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ColorID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModificationDatetime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModificationDatetime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RevisionID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RevisionID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RecurID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RecurID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

src/Mens2020.Mvc/Views/Home/Details.cshtml
@model Mens2020.DataSource.Models.UserEvent

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>UserEvent</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.User.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventTypeId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventTypeId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ParentId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ParentId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompletedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompletedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventText)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ColorID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ColorID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModificationDatetime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModificationDatetime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RevisionID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RevisionID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RecurID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RecurID)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.UserEventId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

src/Mens2020.Mvc/Views/Home/ExpUser.cshtml
@model IEnumerable<Mens2020.DataSource.Models.UserEvent>
@{
    ViewBag.Title = "ExpUser";
}

<h2>Welcome back, @Capstone2020UserExtensions.GetFirstName(User.Identity)! Here are today's goals</h2>




<p>
    @Html.ActionLink("Create New", "CreateQuick", "Home")
</p>
<table class="table">
    <tr>   
        <th>
            @Html.DisplayNameFor(model => model.EventTitle)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.EventText)
        </th>   
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EventTitle)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.EventText)
            </td>           

            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.UserEventId }) |
                @Html.ActionLink("Details", "Details", new { id = item.UserEventId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.UserEventId })
            </td>
        </tr>
    }
</table>
<p>
    @Html.ActionLink("See all goals", "AllGoals", "_Goal")
</p>

src/Mens2020.Mvc/Views/Home/Index.cshtml
@model IEnumerable<Mens2020.DataSource.Models.UserEvent>
@{
    ViewBag.Title = "Home Page";
}

@section scripts{
    <link rel="stylesheet" type="text/css" href="~/Content/AppStyle.css">

    <style>
        tab1 {
            padding-left: 4em
        }
    </style>

    <script>
        var experianced = 0;
        $(window).load(function () {
            if (experianced == true) {
                document.querySelector("#unexperianced-user").style.display = "none";
                document.querySelector("#experianced-user").style.display = "block";
            }
            else { }
        });

        var d = new Date();
        document.getElementById("date").innerHTML = d.toString("d");

    </script>
}



<!-- todo: Add DB output code here.... -->
<!-- todo: (YS) date only! -->
<div class="homepage-header">
    <div style="display:inline-block">
        <p>@User.Identity.Name</p>
        <!-- todo: Coach name needed -->
        <p>COACH NAME</p>
    </div>
    <div style="display:inline-block; margin-left:20px;">
        <!-- todo: (YS) remove after DB code set-up -->
        <button id="switch">Only here to show how "experinced" user homepage works</button>
    </div>
    <div style="float:right">
        <p id="date"></p>
    </div>
</div>
<div id="unexperianced-user" style="display:block">
    <div class="homepage-goal-container">
        <p>
            <br />
            <br />
            <tab1>You have made an account, found yourself a coach, that's Two GOALS Accomplished already.
            <br />
            <br />
            <tab1>The next GOAL is to create a GOAL of your own. Let's get started. Just click on the "Create New Goal" button, and we will walk you through how to Make A GOAL of your own.
            <br /><br />
            <tab1><tab1>@Html.ActionLink("CREATE NEW GOAL", "CreateGuided", "_Goal")
        </p>
    </div>
</div>
<div id="experianced-user" style="display:none">
    <div class="homepage-goal-container">
        <table>
            <tr>
                <th>
                    @Html.DisplayNameFor(Model => Model.EventTitle)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.EventText)
                </th>


            </tr>
        </table>

        @if (Model.Count() > 0)
        {
            foreach (var item in Model)
            {
                <table>
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.EventTitle)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.EventText)
                        </td>

                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.UserEventId }) |
                            @Html.ActionLink("Details", "Details", new { id = item.UserEventId }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.UserEventId })
                        </td>
                    </tr>
                </table>
            }
        }
        else
        {
            <table>
                <tr>
                    <td>
                        You have no active goals at the moment
                    </td>
                </tr>
            </table>

        }
        
    <div style="margin-top:20px">
        @Html.ActionLink("CREATE NEW GOAL", "ChooseCreateType", "_Goal")
    </div>
    </div>
</div>